#Dependencias de desarrollo
FROM node:19.2-alpine3.16 AS deps
WORKDIR /app
COPY package.json ./
RUN npm install


#build y test
FROM node:19.2-alpine3.16 AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules 
COPY . .
RUN npm run test
# RUN npm run build

# Dependencias de produccion
FROM node:19.2-alpine3.16 AS prod-deps
WORKDIR /app
COPY package.json ./
RUN npm install --prod

#Ejecutar la app
FROM node:19.2-alpine3.16 AS runner
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules 
COPY app.js . 
COPY tasks ./tasks

CMD [ "node", "app.js" ]